package compiler

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var goIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func EmitGo(graph Graph, plan GenerationPlan) ([]byte, error) {
	if plan.Language != "go" || !goIdentifier.MatchString(plan.Package) || !goIdentifier.MatchString(plan.Entrypoint) {
		return nil, fmt.Errorf("invalid Go generation plan")
	}
	modules := append([]Module(nil), graph.Modules...)
	sort.Slice(modules, func(i, j int) bool { return modules[i].Identity < modules[j].Identity })
	var output strings.Builder
	output.WriteString("// Code generated by gooo-incremental-module-compiler from .gooo; DO NOT EDIT.\n")
	output.WriteString("package " + plan.Package + "\n\n")
	output.WriteString("import \"fmt\"\n\n")
	output.WriteString("const LinkedSchema = " + strconv.Quote(graph.Schema) + "\n")
	output.WriteString("const LinkedStatus = " + strconv.Quote(string(graph.Status)) + "\n")
	output.WriteString("const LinkedCanonicalDigest = " + strconv.Quote(graph.CanonicalDigest) + "\n\n")
	output.WriteString("var LinkedModules = []string{\n")
	for _, module := range modules {
		output.WriteString("\t" + strconv.Quote(module.Identity) + ",\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("func " + plan.Entrypoint + "() {\n")
	output.WriteString("\tfmt.Println(LinkedSchema, LinkedStatus, LinkedCanonicalDigest, len(LinkedModules))\n")
	output.WriteString("}\n")
	return []byte(output.String()), nil
}
